export const SAGA_INFO_PRODUTO = 'SAGA_INFO_PRODUTO';
export const SAGA_COMPRA_PRODUTO = 'SAGA_COMPRA_PRODUTO';
export const SAGA_LISTA_DESCRICAO_PRODUTO = 'SAGA_LISTA_DESCRICAO_PRODUTO';
export const LOADING = 'LOADING_LOGIN';
export const ADICIONA_PRODUTO = 'ADICIONA_PRODUTO';
export const ADICIONA_DESCRICAO_PRODUTO = 'ADICIONA_DESCRICAO_PRODUTO';
