export const LOADING = 'LOADING_PRODUCT_DETAILS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_DESCRIPTIONS = 'ADD_PRODUCT_DESCRIPTIONS';
export const SAGA_PRODUCT_DETAILS = 'SAGA_PRODUCT_DETAILS';
export const SAGA_BUY_PRODUCT = 'SAGA_BUY_PRODUCT';
export const SAGA_PRODUCT_DESCRIPTIONS = 'SAGA_PRODUCT_DESCRIPTIONS';
