version: '3'

services:
  ml-react-project:
    image: nginx:latest
    container_name: ml-react-project
    volumes:
    - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    - ./build:/usr/share/nginx/html
    ports:
     - 3000:80