export const CLEAR_REDUCER = 'CLEAR_REDUCER_PRODUCT_LIST';
export const LOADING = 'LOADING_PRODUCT_LIST';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const SAGA_PRODUCT_LIST = 'SAGA_PRODUCT_LIST';
