export const Colors = {
  white: '#FFF',
  whiteTransparent: '#ffffff61',
  black: '#000',
  lightWhite: '#E9E9E9',
  blue: '#10727D',
  lightBlue: '#81B0B5',
  secondBlue: '#00E5FF',
  grey: '#6B6B6B',
  lightGrey: '#858585',
  whiteGrey: '#CECECE',
  greyTransparent: '#6b6b6b9c',
  red: '#ff4f4f',
  green: '#00b400',
  greyWhite: '#CCCCCC',
  greyMedium: '#747474',
  whiteBlue: '#CAEDF1',
};

export const Themes = {
  primary: Colors.blue,
  primaryColor: Colors.lightBlue,
  sidebar: Colors.grey,
  sidebarMenu: Colors.lightGrey,
  sidebarButtonTxt: Colors.whiteGrey,
  title: Colors.secondBlue,
  formInvalid: Colors.red,
  greyCard: '#F6F6F6',
  formGreyColor: Colors.lightGgrey,
  formGreyBorder: Colors.greyWhite,
  widthSidebar: '400px',
  heightSidebar: '100%',
  heightHeader: '110px',
};
